-- CreateEnum change: Role
ALTER TYPE "Role" RENAME VALUE 'ADMIN' TO 'OWNER';
ALTER TYPE "Role" RENAME VALUE 'EMPLOYEE' TO 'DEVELOPER';

-- AlterTable
ALTER TABLE "Employee" ADD COLUMN "role" "Role" NOT NULL DEFAULT 'DEVELOPER';
ALTER TABLE "Employee" ADD COLUMN "passwordHash" TEXT NOT NULL DEFAULT 'PLACEHOLDER_WILL_BE_RESEEDED';
ALTER TABLE "Employee" ADD COLUMN "mustChangePassword" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Employee" ALTER COLUMN "passwordHash" DROP DEFAULT;
